[features]
seeds = false
[programs.devnet]
myepicproject = "7gaQqZrSaatVcB6DWo6ubpSh9Yzw798TXkJyvmKVMUmA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/waunbroderick/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
